window.B2B={
nav:['home','courses','corporate','about','contacts'],
PI:'31415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091456485669234603486104543266482133936072602491412737245870066063155881748815209209628292540917153643678925903600113305305488204665213841469519415116094',
courses:[
{id:'01',cat:'team',tone:'green',flagship:true,page:'course-b2b-complex.html',ru:'Управление B2B-продажами — комплексная программа',en:'B2B sales management — comprehensive programme',dru:'Смешанная модель: самостоятельная работа + живые практикумы в группе. 8 недель + 2 недели на защиту, около 70 часов.',den:'Blended: self-study + live group workshops. 8 weeks + 2 weeks for defence, about 70 hours.',weeks:10,hours:70,format:'blended',start:'12/01/27'},
{id:'02',cat:'strategy',tone:'green',ru:'Стратегия B2B-продаж',en:'B2B sales strategy',dru:'Сегментация рынка, ценностное предложение и воронка для сложных сделок с длинным циклом.',den:'Market segmentation, value proposition and a funnel for long-cycle complex deals.',weeks:6,format:'online',start:'02/11/26'},
{id:'03',cat:'clients',tone:'orange',ru:'Управление ключевыми клиентами (KAM)',en:'Key account management (KAM)',dru:'Планирование по аккаунтам, карта влияния, развитие и удержание крупных заказчиков.',den:'Account planning, stakeholder maps, growing and retaining major customers.',weeks:8,format:'offline',start:'16/11/26'},
{id:'04',cat:'clients',tone:'orange',ru:'Сложные переговоры в B2B',en:'Complex B2B negotiations',dru:'Подготовка позиции, работа с закупками и комитетами, торг по цене и условиям.',den:'Positioning, procurement and buying committees, price and terms bargaining.',weeks:4,format:'offline',start:'09/11/26'},
{id:'05',cat:'strategy',tone:'green',ru:'Тендерные продажи и закупки',en:'Tender sales and procurement',dru:'44-ФЗ и 223-ФЗ, корпоративные закупки, подготовка конкурентной заявки.',den:'Public and corporate procurement, building a winning bid.',weeks:5,format:'online',start:'23/11/26'},
{id:'06',cat:'analytics',tone:'violet',ru:'CRM, воронка и аналитика продаж',en:'CRM, funnel and sales analytics',dru:'Метрики отдела, прогнозирование выручки, дашборды и автоматизация в CRM.',den:'Team metrics, revenue forecasting, dashboards and CRM automation.',weeks:6,format:'online',start:'02/11/26'},
{id:'07',cat:'strategy',tone:'green',ru:'Ценообразование и коммерческие предложения',en:'Pricing and commercial proposals',dru:'Ценовые модели, скидочная политика и КП, которое защищает маржу.',den:'Pricing models, discount policy and proposals that protect margin.',weeks:4,format:'blended',start:'30/11/26'},
{id:'08',cat:'team',tone:'greenDark',ru:'Руководитель отдела продаж',en:'Head of sales',dru:'Найм, адаптация, мотивация и операционное управление командой продаж.',den:'Hiring, onboarding, motivation and day-to-day management of a sales team.',weeks:16,format:'blended',start:'07/12/26'},
{id:'09',cat:'clients',tone:'orange',ru:'Продажи технологических решений',en:'Selling technology solutions',dru:'Консультативные продажи инженерных и ИТ-решений, пилоты и ТЭО для заказчика.',den:'Consultative selling of engineering and IT solutions, pilots and business cases.',weeks:8,format:'offline',start:'14/12/26'}],
i18n:{
ru:{school1:'Школа управления',school2:'B2B-продажами',
nav:{home:'Главная',courses:'Все курсы',corporate:'Корпоративное обучение',about:'О школе',contacts:'Контакты'},
tools:{search:'Поиск',lv:'Версия для слабовидящих',theme:'Сменить тему',lang:'Язык: English',cabinet:'Личный кабинет',menu:'Меню'},
eyebrow:'Политех · Дополнительное профессиональное образование',
h1:['Управление','{B2B}-','продажами'],
lead:'Программы повышения квалификации для руководителей отделов продаж, аккаунт-менеджеров и коммерческих директоров промышленных и технологических компаний.',
pick:'Выбрать курс',hint:'Наведите курсор на модель',
facts:[['Ближайший старт','02/11/26'],['9 программ','от 4 до 16 недель'],['Очно и онлайн','Политехническая, 29'],['Удостоверение','о повышении квалификации СПбПУ']],
marquee:['Стратегия продаж','Ключевые клиенты','Сложные переговоры','Тендеры и закупки','CRM и аналитика','Ценообразование','Управление командой'],
cats:{all:'Все',strategy:'Стратегия',clients:'Клиенты и переговоры',analytics:'CRM и аналитика',team:'Команда'},
formats:{online:'Онлайн',offline:'Очно',blended:'Смешанный'},
weeks:'нед.',start:'Старт',more:'Подробнее',scrollHint:'Прокрутите, чтобы листать',
stepsTitle:'Как проходит обучение',
steps:[['Диагностика','Оцениваем воронку, роли и метрики вашего отдела продаж и собираем индивидуальный маршрут.'],['Модули','Лекции и практикумы с преподавателями Политеха и практиками из промышленных компаний.'],['Кейсы','Разбираем реальные сделки слушателей: от квалификации лида до подписания контракта.'],['Итоговый проект','Защита проекта перед экспертной комиссией и удостоверение о повышении квалификации СПбПУ.']],
corpTitle:'Корпоративное обучение',corpLead:'Соберём программу под задачи компании и обучим всю команду продаж — на площадке Политеха или у вас.',
corpOffers:['Программы под задачи компании','Обучение на материалах ваших сделок','Оценка и развитие команды продаж'],
form:{company:'Компания',name:'Контактное лицо',email:'Электронная почта',size:'Размер команды',sizes:['до 10 человек','10–50 человек','50–200 человек','более 200'],agree:'Согласен с политикой обработки персональных данных',send:'Оставить заявку',err:'Укажите корректный адрес'},
aboutTitle:'О школе',aboutText:'Школа управления B2B-продажами — направление дополнительного профессионального образования Санкт-Петербургского политехнического университета Петра Великого. Мы соединяем инженерную культуру Политеха и практику продаж промышленных компаний.',
counters:[[1899,'','год основания Политеха'],[9,'','программ школы'],[40,'+','преподавателей-практиков']],
orgInfo:'Сведения об образовательной организации',policy:'Политика обработки персональных данных',
foot:{nav:'Навигация',contacts:'Контакты',students:'Слушателям',social:'Мы в соцсетях',hours:'Пн–Пт, 10:00–18:00',rights:'Все права защищены.',slogan:'Мыслить будущим',cta:'Подобрать программу'},
toastSent:'Заявка отправлена',toastSentT:'Менеджер свяжется с вами в течение рабочего дня',
search:{ph:'Найти курс',empty:'Ничего не найдено',close:'Закрыть'},
cab:{title:'Личный кабинет',email:'Электронная почта',pass:'Пароль',remember:'Запомнить меня',login:'Войти',ok:'Вы вошли в кабинет'},
cookie:'Мы используем cookie и обрабатываем данные о посещениях в соответствии с ',cookieOk:'Принять'},
en:{school1:'School of',school2:'B2B Sales Management',
nav:{home:'Home',courses:'All courses',corporate:'Corporate training',about:'About',contacts:'Contacts'},
tools:{search:'Search',lv:'Low-vision mode',theme:'Switch theme',lang:'Язык: русский',cabinet:'My account',menu:'Menu'},
eyebrow:'Polytech · Continuing professional education',
h1:['{B2B} sales','manage-','ment'],
lead:'Professional development programmes for heads of sales, account managers and commercial directors of industrial and technology companies.',
pick:'Choose a course',hint:'Hover over the model',
facts:[['Next intake','02/11/26'],['9 programmes','4 to 16 weeks'],['On campus & online','29 Polytechnicheskaya St'],['Certificate','of professional development, SPbPU']],
marquee:['Sales strategy','Key accounts','Complex negotiations','Tenders','CRM & analytics','Pricing','Team management'],
cats:{all:'All',strategy:'Strategy',clients:'Clients & negotiations',analytics:'CRM & analytics',team:'Team'},
formats:{online:'Online',offline:'On campus',blended:'Blended'},
weeks:'wks',start:'Starts',more:'Details',scrollHint:'Scroll to browse',
stepsTitle:'How it works',
steps:[['Assessment','We review your funnel, roles and metrics and build an individual track.'],['Modules','Lectures and workshops with Polytech faculty and industry practitioners.'],['Cases','We work through participants’ real deals, from lead qualification to signed contract.'],['Final project','Project defence before an expert panel and an SPbPU professional development certificate.']],
corpTitle:'Corporate training',corpLead:'We design a programme around your goals and train the whole sales team — on campus or at your site.',
corpOffers:['Programmes tailored to your company','Training on your own deals','Sales team assessment and development'],
form:{company:'Company',name:'Contact person',email:'Email',size:'Team size',sizes:['up to 10','10–50','50–200','200+'],agree:'I agree to the personal data policy',send:'Send request',err:'Enter a valid email'},
aboutTitle:'About the school',aboutText:'The School of B2B Sales Management is a continuing education track of Peter the Great St. Petersburg Polytechnic University, joining Polytech’s engineering culture with the sales practice of industrial companies.',
counters:[[1899,'','Polytech founded'],[9,'','programmes'],[40,'+','practitioner faculty']],
orgInfo:'About the educational organisation',policy:'Personal data policy',
foot:{nav:'Navigation',contacts:'Contacts',students:'Students',social:'Social',hours:'Mon–Fri, 10:00–18:00',rights:'All rights reserved.',slogan:'Think the future',cta:'Find a programme'},
toastSent:'Request sent',toastSentT:'A manager will contact you within one business day',
search:{ph:'Find a course',empty:'Nothing found',close:'Close'},
cab:{title:'My account',email:'Email',pass:'Password',remember:'Remember me',login:'Sign in',ok:'Signed in'},
cookie:'We use cookies and process visit data in accordance with the ',cookieOk:'Accept'}}
};
